server:
    port: 8080
    servlet:
        context-path: /

management:
    endpoints:
        web:
            base-path: /manage
            exposure:
                include: health,info

# These values are configured for use with a local DSE Cassandra Docker container
# Refer to readme for instructions on creating a new image for use with these configurations
spring:
    data:
        cassandra:
            # Change this address to the local network address of your physical machine!!
            contact-points: 192.168.1.139
            keyspace-name: "my_retail"
